name: Annotate CI run with test results
on:
  workflow_run:
    workflows: [ "Continuous Integration" ]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  annotate:
    name: Annotate CI run with Tests Results
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download results
        uses: actions/download-artifact@v4
        with:
          pattern: magic-assets-test-results-*
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Annotate CI run with Tests Results
        uses: dorny/test-reporter@v1.8.0
        with:
          name: Results
          path: "*.trx"
          reporter: dotnet-trx
          list-suites: 'failed'
          list-tests: 'failed'
